### ISSUE TITLE
Scrolling up using the 'k' key is broken

### ISSUE THREAD

**Issue by rchard2scout** [bjornstar/Tumblr-Savior#7] opened 2014-06-10 12:06 UTC
When a post is hidden, trying to scroll up on that page using the 'k' key no longer scrolls up an entire post. Instead, it scrolls up a few pixels. This only happens on a page where a post is blocked, and it doesn't matter whether or not a notification is shown.

**Comment by bjornstar** [comment] 2015-04-09 03:07
I really wish I knew what caused this, I generally don't use the j & k shortcuts when I'm on tumblr. I'd really love it if someone could figure out how to fix it.

**Comment by Izzette** [comment] 2015-04-09 14:40
I'll look into it.

**Comment by Izzette** [comment] 2015-04-09 16:47
Okay, I've installed the latest pull of Tumblr-Savior into the Firefox nightly-build.  And, I was able to reproduce the bug.

**Comment by agnesnutter** [comment] 2015-12-07 06:23
Any updates on this bug?

**Comment by JogaLuce** [comment] 2016-03-13 01:38
I am not able to reproduce this bug in ff33.0.1 && ts0.4.22.1.

**Comment by bjornstar** [comment] 2016-03-13 01:47
Actually, I may have this fixed for the next release ;)

**Comment by bjornstar** [comment] 2016-03-13 02:53
Fixed in v0.4.25

**Closed by bjornstar** 2016-03-13 02:53 UTC
